### PR TITLE
Added a way to get data for years in range

### PR DESCRIPTION
**Pull request by Hoffs**
Solution for #4 . Fetches data for range of years and concats the results.

### CODE REVIEW

**Comment by jaydp17** [comment]
@Hoffs- your solution works!!
But it's serial, can you please make it concurrent?

**Comment by Hoffs** [comment]
is it better this way?

**Comment by jaydp17** [comment]
ya, this seems better 🙂
One more thing I noticed in the range function that you've written is `end`  parameter in that is exclusive.

Thus when you pass `range(2017, 2018)` it returns `[2017]`.
You'll have to pass `range(2017, 2019)` to get `[2017, 2018]`

Just change that, then I can merge this!

**Comment by Hoffs** [comment]
changed the length to be at least 1 unless negative.

**Pull request merged**
